[package]
name = "mixed-pickles"
version = "0.2.2"
edition = "2024"

[lib]
name = "mixed_pickles"
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pyo3 = { version = "0.27.2", features = ["extension-module"] }
regex = "1"
thiserror = "2.0"
